version: "3.9"
services:
  backend:
    build: .
    container_name: aren-backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8000:8000"
    volumes:
      - ./:/workspace/aren-transcriber
    env_file:
      - .env
    runtime: nvidia

  frontend:
    image: node:20-bullseye
    container_name: aren-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]